# Generated by Django 4.0 on 2024-02-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_contact_profile_alter_project_image_alter_skill_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fblink', models.URLField()),
                ('instalink', models.URLField()),
                ('xlink', models.URLField()),
                ('tglink', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='about',
            name='image1',
            field=models.ImageField(upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='about',
            name='image2',
            field=models.ImageField(upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='home',
            name='image',
            field=models.ImageField(upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cv_image',
            field=models.ImageField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='logo',
            field=models.ImageField(upload_to='files/'),
        ),
    ]
