# Generated by Django 4.0 on 2024-03-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_fblink_social_link_remove_social_instalink_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='social',
            old_name='link',
            new_name='fblink',
        ),
        migrations.RemoveField(
            model_name='social',
            name='name',
        ),
        migrations.AddField(
            model_name='social',
            name='instalink',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='social',
            name='tglink',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='social',
            name='xlink',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
